### ISSUE TITLE
Add parameter for random seed

### ISSUE THREAD

**Issue by murphycj** [cbg-ethz/COMPASS#10]
Hello!

Can you add a parameter for a random seed so a single analysis can be fully reproduced? MCMC by its very nature has randomness, but for the purpose of testing non-COMPASS parts of my pipeline I'd like to keep COMPASS results constant.

Is that possible?

**Comment by e-sollier** [comment]
Hi,

Currently, COMPASS uses seeds internally. The arguments --nchains (default: 4) sets the number of MCMCs that are run in parallel, and for the _i_-th chain, the seed _i_ is used. If this would be useful for you, I can easily expose a parameter to alter the seeds instead of always using the same ones, but in the current state COMPASS should already provide reproducible results. Did you observe cases where, with the same input, COMPASS produced a different output ? If so I could try to investigate what might be causing this.

**Comment by murphycj** [comment]
Sorry for the late reply, and thanks for the response. I do not need you to expose the random seed parameters.

But I attached a zip file containin an example dataset where I am seeing some some variation in results (though it is rare). See `test_variants.csv` and `test_regions.csv` for the input. I ran 15 iterations, where 13 iterations of the them gave 4 clones but 2 iterations gave 3 clones (`test13` and `test6`).

**test6_nodes_genotypes.tsv** (3 clones)
```
node	Gene45 (p.G12S)	Gene17 (p.R882H)	Gene24 (p.R132H)	Gene61 (p.K1920*)	Gene44 (p.W288Cfs*12)	Gene21 (ITD) (chr13:28608223:./TCATATTCATATTCTCTGAAA)	Gene51 (p.P96S)	Gene4 (p.E865K)
Node 0	0	0	0	0	0	0	0	1
Node 1	1	1	1	1	1	1	0	1
Node 2	1	1	1	1	1	1	1	1
```

**test5_nodes_genotypes.tsv** (4 clones)
```
node	Gene45 (p.G12S)	Gene17 (p.R882H)	Gene24 (p.R132H)	Gene61 (p.K1920*)	Gene44 (p.W288Cfs*12)	Gene21 (ITD) (chr13:28608223:./TCATATTCATATTCTCTGAAA)	Gene51 (p.P96S)	Gene4 (p.E865K)
Node 0	0	0	0	0	0	0	0	1
Node 1	1	1	1	1	1	1	1	1
Node 2	1	1	1	1	1	1	0	1
Node 3	1	1	1	0	1	1	0	1
```


I used this command.
```
COMPASS --CNV 0 --nchains 4 --chainlength 5000 -i test -o test15
```




[test_compass.zip](https://github.com/cbg-ethz/COMPASS/files/12235399/test_compass.zip)

**Comment by e-sollier** [comment]
Thanks for your report. I tested on your example dataset, and I can confirm that I also see that COMPASS can output different trees for this dataset, even when all parameters are the same. I have briefly tried to look at what might be causing this lack of reproducibility, but so far I have not been able to find the cause. If this is important to you I can try to spend more time to identify the reason, but otherwise I think it's maybe not too critical.

One imperfect workaround would be to increase the chainlength. That way, each iteration has a higher chance to find the tree with the best score, which increases the chances that all iterations give the same result. On the example that you provided, if I increase the chainlength to 15000, then all 15 trees are the same.

**Comment by murphycj** [comment]
Thanks for looking into this and for the tip about increasing chain length. I'll close this issue for now.
