### ISSUE TITLE
Is this compatible with time series data?

### ISSUE THREAD

**Issue by murphycj** [cbg-ethz/COMPASS#6]
In your opinion, is it valid to combine multiple samples from the same patient (i.e. time series) and input it into COMPASS? It would seem to me that phylogeny reconstruction with just variants should be fine, but I'm less sure about the effects on CNV/LOH calling.

Thank you!

**Comment by e-sollier** [comment]
Hello,

I have not tested it, but I guess it should be fine to combine several longitudinal samples into one, as long as the same panel was used for all samples. Just make sure that the read counts in each region are based on the same amplicons for all samples (sometimes, the loom files generated by the Tapestri pipeline do not contain information for all amplicons).

One thing to keep in mind is that when attaching a cell to a node, COMPASS uses both the likelihood of the observed read counts given the genotype of the node, as well as a prior probability of the node, which is based on the proportion of cells attached to this node. If you combine several longitudinal samples into one sample, the prior probabilities of the node will not depend on which sample the cell came from. This should not be a problem for the tree itself, but might lead to some cells being wrongly attached. If a mutation was not present in one sample but is present in many cells of other samples, the nodes with this mutation will have a high prior probability. It could then be that cells without the mutation are attached to a node with the mutation, since having a dropout of the mutated allele might be more likely than being attached to a node with a lower prior probability. So if you combine multiple longitudinal samples into one and you see that a small proportion of cells from one of the samples contain a mutation or CNA, I would not necessarily consider this as evidence that the mutation was already present in this sample.

I hope this is clear, let me know if you have other questions!

**Comment by murphycj** [comment]
Thank you, that makes a lot of sense. I've been doing some testing and that is indeed what I see happen, but I find this node mis-assignment usually happens to only a handful of cells (<0.5% of cells). I was also exploring a simple "node correction" algorithm that reassigns cells to the appropriate node (if available) based on the knowledge of what variants were called in each time point. Fixes the vast majority of these mis-assignments.
