### ISSUE TITLE
Is it possible to annotate cells?

### ISSUE THREAD

**Issue by RaphaelHablesreiter** [cbg-ethz/COMPASS#7]
Hi,

thank you for this awesome tool.
Is it possible to include additional information for each cell?  In detail, I have information of a gene fusion for each cell (-> only alt reads if fusion is there).

Many thanks!

**Comment by e-sollier** [comment]
Hi,

Thanks for your interest in COMPASS!
I am not sure I understand what you mean. Do you want to include this fusion in the phylogeny ? Then I would recommend considering it as an SNV in the input that you give to COMPASS. I don't know how you get this fusion information, but I guess you must have a number of reads which support the fusion and a number of reads which do not, and you can use this instead of the number of reads with the REF or ALT allele in the _variants.csv input file.

**Comment by RaphaelHablesreiter** [comment]
The problem is that I only have ALT reads, because if the cell has the fusion there are reads and if not there are no reads at all. So my data is for the fusion is either 0:0:0 or 0:ALT_reads:2. 
That is why I was asking if it is possible to somehow annotate them, so that standard filters/models are not applied to this "mutation".

**Comment by e-sollier** [comment]
Ah I see, so you have one primer on each side of the fusion ?
This is interesting, I did not know that such amplicons were used with the Tapestri platform, although I can see that it could be very useful in some cases. COMPASS does not currently explicitly model this, but here is what I would recommend you to do, which should work well:
- give the fusion as an SNV as input to COMPASS
- when there is no read for the fusion, set the allelic read counts to 10:0:0 (10 ref reads and 0 alt) in the _variants.csv file. The 10 is arbitrary, any value >5 should be fine. Ideally you could set this value to the mean number of reads that you detect when the fusion is present. This is because if you set the read counts to 0:0:0, COMPASS will assume that we have no information at all for the fusion, so having or not having the fusion will be equally likely, whereas the fact that you do not detect any reads for the fusion actually provides evidence that the fusion is not present.
- when there are reads for the fusion, set the allelic read counts to X:X:1, where X is the number of reads that cover the fusion.
- assign the variant corresponding to the fusion to a new region, and set the read counts in this region to 0 for all cells (in the _regions.csv file). This will exclude the region from the CNV inferrence. 

Let me know if this works, I would be interested to know if COMPASS is also applicable to such cases!

**Comment by e-sollier** [comment]
Ah I see, so you have one primer on each side of the fusion ?
This is interesting, I did not know that such amplicons were used with the Tapestri platform, although I can see that it could be very useful in some cases. COMPASS does not currently explicitly model this, but here is what I would recommend you to do, which should work well:
- give the fusion as an SNV as input to COMPASS
- when there is no read for the fusion, set the allelic read counts to 10:0:0 (10 ref reads and 0 alt) in the _variants.csv file. The 10 is arbitrary, any value >5 should be fine. Ideally you could set this value to the mean number of reads that you detect when the fusion is present. This is because if you set the read counts to 0:0:0, COMPASS will assume that we have no information at all for the fusion, so having or not having the fusion will be equally likely, whereas the fact that you do not detect any reads for the fusion actually provides evidence that the fusion is not present.
- when there are reads for the fusion, set the allelic read counts to X:X:1, where X is the number of reads that cover the fusion.
- assign the variant corresponding to the fusion to a new region, and set the read counts in this region to 0 for all cells (in the _regions.csv file). This will exclude the region from the CNV inferrence. 

Let me know if this works, I would be interested to know if COMPASS is also applicable to such cases!

**Comment by RaphaelHablesreiter** [comment]
Many thanks! I will try that and let you know!
